var htmlstr='<div class="container-fluid footerTOP">';
htmlstr = htmlstr + '<div class="row">';
htmlstr = htmlstr + '<div class=" col-xs-12 col-sm-12 footerbgs  visible-xs">';
htmlstr = htmlstr + '<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">';
htmlstr = htmlstr + '<div class="container">';
htmlstr = htmlstr + '<div class="row">';
htmlstr = htmlstr + '<div class="panel-default">';
htmlstr = htmlstr + '<div class="panelanel-heading" role="tab" id="panel1">';
htmlstr = htmlstr + '<a href="#aaa" data-parent="#accordion" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="aaa">';
htmlstr = htmlstr + '<h4 class="panel-title">使用Lingvist</h4>';
htmlstr = htmlstr + '</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div id="aaa" class="panel-collapse collapse" role="tabpanel" aria-labelledby="panel1">';
htmlstr = htmlstr + '<div class="list-group">';
htmlstr = htmlstr + '<a href="https://go.lingvist.com/signin?language=zh-Hant" target="_blank" class="list-group-item">線上登入</a>';
htmlstr = htmlstr + '<a href="http://www.lingvist.com.tw/inclient_j/inclient2?pid=pid04345&evtType=lingvist" target="_blank" class="list-group-item">';
htmlstr = htmlstr + '<img src="/imgs/common/appdown_appstore.png" style="width:128px;margin-bottom: 7px;" alt="App Store">';
htmlstr = htmlstr + '</a>';
htmlstr = htmlstr + '<a href="https://play.google.com/store/apps/details?id=io.lingvist.android" target="_blank" class="list-group-item">';
htmlstr = htmlstr + '<img src="/imgs/common/appdown_googleplay.png" style="width: 128px;" alt="Google Play"></a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div class="container">';
htmlstr = htmlstr + '<div class="row">';
htmlstr = htmlstr + '<div class="panel-default">';
htmlstr = htmlstr + '<div class="panelanel-heading" role="tab" id="panel2">';
htmlstr = htmlstr + '<a href="#bbb" data-parent="#accordion" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="bbb">';
htmlstr = htmlstr + '<h4 class="panel-title">服務介紹</h4>';
htmlstr = htmlstr + '</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div id="bbb" class="panel-collapse collapse" role="tabpanel" aria-labelledby="panel2">';
htmlstr = htmlstr + '<div class="list-group">';
htmlstr = htmlstr + '<a href="/features/index.html" class="list-group-item">Lingvist 特色</a>';
htmlstr = htmlstr + '<a href="/share/feedback/index.html" class="list-group-item">實證分享</a>';
htmlstr = htmlstr + '<a href="/help/faq.html" class="list-group-item">常見問題</a>';
htmlstr = htmlstr + '<a href="/help/contact.html" class="list-group-item">問題回報</a>';
htmlstr = htmlstr + '<a href="/news/index.html" class="list-group-item">News</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div class="container">';
htmlstr = htmlstr + '<div class="row">';
htmlstr = htmlstr + '<div class="panel-default">';
htmlstr = htmlstr + '<div class="panelanel-heading" role="tab" id="panel4">';
htmlstr = htmlstr + '<a href="#ddd" data-parent="#accordion" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="ddd">';
htmlstr = htmlstr + '<h4 class="panel-title">關於</h4>';
htmlstr = htmlstr + '</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div id="ddd" class="panel-collapse collapse" role="tabpanel" aria-labelledby="panel4">';
htmlstr = htmlstr + '<div class="list-group">';
htmlstr = htmlstr + '<a href="/about-us/index.html" class="list-group-item">關於我們</a>';
htmlstr = htmlstr + '<a href="/help/tos.html" class="list-group-item">服務約定條款</a>';
htmlstr = htmlstr + '<a href="/help/privacy.html" class="list-group-item">隱私權條款</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div class="container">';
htmlstr = htmlstr + '<div class="row">';
htmlstr = htmlstr + '<div class="panel-default">';
htmlstr = htmlstr + '<div class="panelanel-heading" role="tab" id="panel3">';
htmlstr = htmlstr + '<a href="#ccc" data-parent="#accordion" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="ccc">';
htmlstr = htmlstr + '<h4 class="panel-title">社群</h4>';
htmlstr = htmlstr + '</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div id="ccc" class="panel-collapse collapse" role="tabpanel" aria-labelledby="panel3">';
htmlstr = htmlstr + '<div class="list-group">';
htmlstr = htmlstr + '<a href="https://www.lingvist.com.tw/blog/index.html" class="list-group-item">Blog</a>';
htmlstr = htmlstr + '<a href="https://www.facebook.com/lingvisttw/" target="_blank" class="list-group-item">Facebook粉絲團</a>';
htmlstr = htmlstr + '<a href="https://line.me/R/ti/p/%40bcu3429a" target="_blank" class="list-group-item">Line官方帳號</a>';
htmlstr = htmlstr + '<a href="https://www.youtube.com/channel/UCHPDgPbOJ9y9yRvYKosRgBw" target="_blank" class="list-group-item">Youtube</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div class="footer_map hidden-xs">';
htmlstr = htmlstr + '<div class="container">';
htmlstr = htmlstr + '<div class="row">';
htmlstr = htmlstr + '<div class="col-md-12 col-lg-12 visible-sm visible-md visible-lg" style=" z-index: 9998;">';
htmlstr = htmlstr + '<div class="col-xs-12 col-md-3 col-lg-3 col-sm-3">';
htmlstr = htmlstr + '<a href="/index.html" title="Lingvist" class="footer_lingvist_logo" alt="Lingvist">Lingvist</a>';
htmlstr = htmlstr + '<a href="/about-us/index.html" title="Linktel" class="footer_linktel_logo" alt="Linktel">Linktel</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div class="col-md-2 col-lg-2 col-sm-2">';
htmlstr = htmlstr + '<div class="list-group">';
htmlstr = htmlstr + '<span class="list-group-item-heading">';
htmlstr = htmlstr + '<h4>使用Lingvist</h4>';
htmlstr = htmlstr + '</span>';
htmlstr = htmlstr + '<a href="https://go.lingvist.com/signin?language=zh-Hant" target="_blank" class="list-group-item" >線上登入</a>';
htmlstr = htmlstr + '<a href="http://www.lingvist.com.tw/inclient_j/inclient2?pid=pid04345&evtType=lingvist" target="_blank" class="list-group-item">';
htmlstr = htmlstr + '<img src="/imgs/common/appdown_appstore.png" style="width: 70%;margin-bottom: 7px;" alt="App Store"></a>';
htmlstr = htmlstr + '<a href="https://play.google.com/store/apps/details?id=io.lingvist.android" target="_blank" class="list-group-item">';
htmlstr = htmlstr + '<img src="/imgs/common/appdown_googleplay.png" style="width: 70%;" alt="Google Play">';
htmlstr = htmlstr + '</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div class="col-md-2 col-lg-2 col-sm-2">';
htmlstr = htmlstr + '<div class="list-group">';
htmlstr = htmlstr + '<span class="list-group-item-heading">';
htmlstr = htmlstr + '<h4>服務介紹</h4>';
htmlstr = htmlstr + '</span>';
htmlstr = htmlstr + '<a href="/features/index.html" class="list-group-item">Lingvist 特色</a>';
htmlstr = htmlstr + '<a href="/share/feedback/index.html" class="list-group-item">實證分享</a>';
htmlstr = htmlstr + '<a href="/help/faq.html" class="list-group-item">常見問題</a>';
htmlstr = htmlstr + '<a href="/help/contact.html" class="list-group-item">問題回報</a>';
htmlstr = htmlstr + '<a href="/news/index.html" class="list-group-item">News</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div class="col-md-2 col-lg-2 col-sm-2">';
htmlstr = htmlstr + '<div class="list-group">';
htmlstr = htmlstr + '<span class="list-group-item-heading">';
htmlstr = htmlstr + '<h4>關於</h4>';
htmlstr = htmlstr + '</span>';
htmlstr = htmlstr + '<a href="/about-us/index.html" class="list-group-item">關於我們</a>';
htmlstr = htmlstr + '<a href="/help/tos.html" class="list-group-item">服務約定條款</a>';
htmlstr = htmlstr + '<a href="/help/privacy.html" class="list-group-item">隱私權條款</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<div class="col-md-3 col-lg-3 col-sm-3">';
htmlstr = htmlstr + '<div class="list-group">';
htmlstr = htmlstr + '<span class="list-group-item-heading">';
htmlstr = htmlstr + '<h4>社群</h4>';
htmlstr = htmlstr + '</span>';
htmlstr = htmlstr + '<a href="https://www.lingvist.com.tw/blog/" class="list-group-item">';
htmlstr = htmlstr + '<i class="fas fa-chevron-circle-right"></i> Blog</a>';
htmlstr = htmlstr + '<a href="https://www.facebook.com/lingvisttw/" target="_blank" class="list-group-item">';
htmlstr = htmlstr + '<i class="fab fa-facebook-square"></i> FB粉絲團</a>';
htmlstr = htmlstr + '<a href="https://line.me/R/ti/p/%40bcu3429a" target="_blank" class="list-group-item">';
htmlstr = htmlstr + '<i class="fa fa-comment" aria-hidden="true"></i> Line官方帳號</a>';
htmlstr = htmlstr + '<a href="https://www.youtube.com/channel/UCHPDgPbOJ9y9yRvYKosRgBw" target="_blank" class="list-group-item">';
htmlstr = htmlstr + '<i class="fab fa-youtube" aria-hidden="true"></i> Youtube</a>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '<footer class="copyright_box">';
htmlstr = htmlstr + '<div class="container">';
htmlstr = htmlstr + '<div class="row">';
htmlstr = htmlstr + '<div class="copyright">';
htmlstr = htmlstr + '<div class="col-md-12">連科通訊股份有限公司版權所有  &nbsp; 轉載必究 &copy;2020 LinkTel Inc.</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</div>';
htmlstr = htmlstr + '</footer>';document.writeln(htmlstr);